In [1]:
'''
【课程1.6】  Numpy数据的输入输出

numpy读取/写入数组数据、文本数据

'''

'\n【课程1.6】  Numpy数据的输入输出\n\nnumpy读取/写入数组数据、文本数据\n\n'

In [5]:
# 存储数组数据 .npy文件

import os
import numpy as np
path = '/Users/matao/Study/data_Analyst/data_ch03'
os.chdir(path)

ar = np.random.rand(5,5)
print(ar)
np.save('arraydata_test02.npy', ar)


[[ 0.85650202  0.29047888  0.20880459  0.33690116  0.27922114]
 [ 0.56478631  0.24139015  0.04206617  0.00854643  0.10071381]
 [ 0.07261429  0.63334495  0.6893219   0.03869285  0.04465471]
 [ 0.02719811  0.78531457  0.79617979  0.05300653  0.25290716]
 [ 0.30157953  0.46946735  0.90277693  0.6016807   0.82201841]]


In [6]:
# 读取数组数据 .npy文件
ar_load = np.load('arraydata_test02.npy')
print(ar_load)


[[ 0.85650202  0.29047888  0.20880459  0.33690116  0.27922114]
 [ 0.56478631  0.24139015  0.04206617  0.00854643  0.10071381]
 [ 0.07261429  0.63334495  0.6893219   0.03869285  0.04465471]
 [ 0.02719811  0.78531457  0.79617979  0.05300653  0.25290716]
 [ 0.30157953  0.46946735  0.90277693  0.6016807   0.82201841]]


In [10]:
# 存储/读取文本文件

# np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')：存储为文本txt文件
ar = np.random.rand(5,5)
np.savetxt('arraydata_test03.txt', ar, delimiter=',')

ar_loadtxt = np.loadtxt('arraydata_test03.txt',delimiter=',')
print(ar_loadtxt)


[[ 0.23494559  0.00620194  0.03769591  0.69010085  0.98198531]
 [ 0.21914959  0.75445098  0.32009283  0.80240473  0.49388489]
 [ 0.84384201  0.99639314  0.77370161  0.41478984  0.25882112]
 [ 0.35156219  0.32040508  0.33116534  0.48662238  0.94399471]
 [ 0.33931395  0.16955524  0.41925276  0.94892698  0.38255115]]


In [19]:
#作业1：创建一个10*10的整数随机数组，取值范围为0-100，并存为txt文件，用逗号分开


hw_ar1 = np.random.randint(0,100,size=(10,10))
np.savetxt('homework1_6.txt',hw_ar1, fmt='%i', delimiter=',')
#print(hw_ar1)

hw_ar2 = np.loadtxt('homework1_6.txt',delimiter=',',dtype=int)
print(hw_ar2)


[[59 25 91 84 49 46 29 49 42 98]
 [63 75 20 89 62 52 60 39 94 62]
 [35 12 46  5 37  9  4 27 35 41]
 [ 4 15 19 66 42 81 88 33 27 98]
 [66  7 69 30 37 72 21 74 66 94]
 [24 87 30 81 86 10 96 74 11 73]
 [77 77 40 53 73 56 48 87 73 80]
 [20 39 26 88  9 11 10 95 98 29]
 [51 20  8  7 24 68 79 13 30 56]
 [29 12 10 67 13 63 86 68 88  7]]
