In [4]:
'''
【课程1.3】  Numpy通用函数

基本操作

'''


'\n【课程1.3】  Numpy通用函数\n\n基本操作\n\n'

In [34]:
# 数组形状：.T/.reshape()/.resize()
import numpy as np
ar1 = np.arange(10)
ar2 = np.ones((5,2))
# print(ar1, '\n', ar1.T)
# print(ar2, '\n', ar2.T)

def arr_info(s):
    print('===============')
    print('数组：',s)
    print('数组dtype：',s.dtype)
    print('数组shape：',s.shape)
    print('数组ndim：',s.ndim)
    print('数组size：',s.size)
    print('数组itemsize：',s.itemsize)
    print('===============\n')

# reshape用法
# numpy.reshape(a, newshape, order='C')：为数组提供新形状，而不更改其数据，所以元素数量需要一致！！
ar3 = ar1.reshape(2,5) # 用法1：直接将已有数组改变形状
ar4 = np.zeros((4,6)).reshape(3,8) # 用法2：生成数组后直接改变形状
ar5 = np.reshape(np.arange(12),(3,4)) # 用法3：参数内添加数组和目标形状---如第一个参数就是一个要生成的一维数组，第二个参数是新的shape的形状
# print(ar1,'\n',ar3)
# print(ar4)
# print(ar5)
# print('------')

# resize用法
# numpy.resize(a, new_shape)：返回具有指定形状的新数组，如有必要可重复填充所需数量的元素。
ar6= np.resize(np.arange(5),(3,4))
print(ar6)

# 注意了：.T/.reshape()/.resize()都是生成新的数组！！！

[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


In [41]:
# 数组的复制

ar1 = np.arange(10)
ar2 = ar1 # 所以这个过程，就是ar2指向和ar1同样的那个数组。
print(ar2 is ar1)
ar1[2] = 9
print(ar1, ar2)

ar3 = ar1.copy() # 所以这个过程：生成数组及其数据的完整拷贝
print(ar3 is ar1)
ar1[0] = 9
print(ar1, ar3)


True
[0 1 9 3 4 5 6 7 8 9] [0 1 9 3 4 5 6 7 8 9]
False
[9 1 9 3 4 5 6 7 8 9] [0 1 9 3 4 5 6 7 8 9]


In [43]:
# 数组类型转换：.astype()

ar1 = np.arange(10, dtype=float)
print(ar1, ar1.dtype)
print('----------')

ar2 = ar1.astype(np.int32)
print(ar2, ar2.dtype)
print(ar1, ar1.dtype)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.] float64
----------
[0 1 2 3 4 5 6 7 8 9] int32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.] float64


In [62]:
# 数组堆叠

# numpy.hstack(tup)：水平（按列顺序）堆叠数组
a = np.arange(5)
b = np.arange(5, 9)
ar1 = np.hstack((a,b)) # 注意:((a,b))，这里形状可以不一样
# print(a, a.shape)
# print(b, b.shape)
# print(ar1, ar1.shape)

a = np.array([[1],[2],[3]])
b = np.array([['a'],['b'],['c']])
ar2 = np.hstack((a,b)) # 注意:((a,b))，这里形状必须一样
# print(a, a.shape)
# print('----------')
# print(b, b.shape)
# print('----------')
# print(ar2, ar2.shape)
# print('----------')


# numpy.vstack(tup)：垂直（按列顺序）堆叠数组
a = np.arange(5)
b = np.arange(5, 10)
ar1 = np.vstack((a,b))  # 注意:((a,b))，这里形状必须一样
# print(a, a.shape)
# print(b, b.shape)
# print(ar1, ar1.shape)

a = np.array([[1],[2],[3]])
b = np.array([['a'],['b'],['c'],['d']])
ar2 = np.vstack((a,b))   # 这里形状可以不一样,正好和平行堆叠相反的。
                        #如果再复杂一点，通过画图就很容易理解。需要记住区分vstack是垂直，hstack是平行
# print(a, a.shape)
# print(b, b.shape)
# print(ar2, ar2.shape)

# numpy.stack(arrays, axis=0)：沿着新轴连接数组的序列，形状必须一样！
a = np.arange(5)
b = np.arange(5, 10)
ar1 = np.stack((a,b))
ar2 = np.stack((a,b), axis = 1) #对二维数组来说，就两个轴，x轴（0轴），y轴（1轴）
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)
print(ar2,ar2.shape)

# 重点解释axis参数的意思，假设两个数组[1 2 3]和[4 5 6]，shape均为(3,0)
# axis=0：[[1 2 3] [4 5 6]]，shape为(2,3)
# axis=1：[[1 4] [2 5] [3 6]]，shape为(3,2)！！！！！！！




[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] (5, 2)


In [76]:
# 数组拆分 

ar = np.arange(16).reshape(4,4)
ar1 = np.hsplit(ar,2)
print(ar)
# print(ar1,type(ar1))

ar2 = np.vsplit(ar, 4)
print(ar2, type(ar2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])] <class 'list'>


In [98]:
# 数组简单运算

ar = np.arange(6).reshape(2,3)
# print(ar + 10)
# print(ar * 2)
# print(1 / (ar+1))
# print(ar**0.5)

print('平均值：',ar.mean())
print('最大值：',ar.max())
print('最小值：',ar.min())
print('标准差：',ar.std())
print('方差：',ar.var())
print('求和：',ar.sum())
print('按列求和：',np.sum(ar,axis=0))
print('按行求和：',np.sum(ar,axis=1))
print('排序1',np.sort(np.array([1,4,3,2,5,6])))
print('排序2',np.sort(np.array([[1,4,3],[2,5,6]])))

平均值： 2.5
最大值： 5
最小值： 0
标准差： 1.70782512766
方差： 2.91666666667
求和： 15
按列求和： [3 5 7]
按行求和： [ 3 12]
排序1 [1 2 3 4 5 6]
排序2 [[1 3 4]
 [2 5 6]]


In [108]:
#作业1：创建一个20个元素的数组，分别改变成两个形状：(4,5),(5,6) （提示：超出范围用resize）

hw_ar1 = np.arange(20).reshape(4,5)
print(hw_ar1)
print('----------')

hw_ar2 = np.resize(np.arange(20),(5,6))
print(hw_ar2)




[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
----------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [113]:
#作业2：创建一个(4,4)的数组，把其元素类型改为字符型

hw_ar3 = np.arange(16).reshape(4,4).astype(str)
print(hw_ar3)



[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [123]:
#作业3：根据要求创建数组，运用数组的运算方法得到结果：result = ar * 10 +100，并求出result的均值及求和

hw_ar4 = np.arange(16).reshape(4,4)
print(hw_ar4)

print('-----------')
result = hw_ar4*10 +100
print(result)
print('-----------')
avg = result.sum()/16
print(avg)
print('-----------')
print(result.sum())


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------
[[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]]
-----------
175.0
-----------
2800
