In [4]:
'''
【课程1.4】  Numpy索引及切片

核心：基本索引及切片 / 布尔型索引及切片

'''

'\n【课程1.4】  Numpy索引及切片\n\n核心：基本索引及切片 / 布尔型索引及切片\n\n'

In [30]:
# 基本索引及切片
import numpy as np

print('\n============一维数组==============')
ar = np.arange(20)
print(ar)
print(ar[4]) # 一维数组索引
print(ar[3:6]) # 一维数组切片

print('\n=============二维数组==============')
ar = np.arange(16).reshape(4,4)
print(ar,'数组ndim为：%i' %ar.ndim) 
print(ar[2], '数组轴数为%i' %ar[2].ndim)# 二维数组索引，切片为一个一维数组
print(ar[2][1]) # 二次索引，得到一维数组中的一个值
print(ar[1:3],'数组轴数为%i' %ar[1:3].ndim) # 二位数组切片，切片还是为二位数组，只是元素数目有变化
print(ar[2,2]) # 切片，同二次索引
print(ar[:2,1:])# 参数1：横向数据，纵向对比向下，参数2：纵向数据，横向对比向右（简单记忆：参数1-向下，参数2-向右）

print('\n============三维数组==============')
ar = np.arange(8).reshape(2,2,2)
print(ar, '数组轴数为%i' %ar.ndim) 
print(ar[0],'数组轴数为%i' %ar[0].ndim) #三维数组的第一个元素---二维数组
print(ar[0][0],'数组轴数为%i' %ar[0][0].ndim) # 由上得到的二位数组的第一个元素 --- 一维数组
print(ar[0][0][1],'数组轴数为%i' %ar[0][0][1].ndim) # 最后由一位数组通过索引找到元素。



============一维数组==============
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[3 4 5]

=============二维数组==============
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 数组ndim为：2
[ 8  9 10 11] 数组轴数为1
9
[[ 4  5  6  7]
 [ 8  9 10 11]] 数组轴数为2
10
[[1 2 3]
 [5 6 7]]

============三维数组==============
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 数组轴数为3
[[0 1]
 [2 3]] 数组轴数为2
[0 1] 数组轴数为1
1 数组轴数为0


In [44]:
# 布尔型索引及切片

ar = np.arange(12).reshape(3,4)
i = np.array([True, False, True])
j = np.array([True, True, False, False])
print(ar)
# print(i)
# print(j)

# print(ar[i,:]) # 参数1：向下，简单书写格式：ar[i,:] = ar[i]
# print(ar[:,j]) # 参数2：向右，这个没有简单书写格式，默认第一个元素为参数1，参数1只能向下，向右的话，元素数量多了，会报错。


m = ar > 5   # 这个地方很有意思！！！！可以直接生成一个矩阵
print(m) # 这里m是一个判断矩阵
print(ar[m])  # # 用m判断矩阵去筛选ar数组中>5的元素 → 重点！后面的pandas判断方式原理就来自此处 !!!!!!!


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


In [52]:
# 数组索引及切片的值更改、复制

ar = np.arange(10)
#print(ar)
ar[5] = 100
ar[7:9] = 200
#print(ar)
# 一个标量赋值给一个索引/切片时，会自动改变/传播原始数组
# 也就是说给数组的元素负值，会修改数组的原始数据

ar = np.arange(10)
b = ar.copy()
b[7:9] = 200
print(ar)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6 200 200   9]


In [59]:
# 作业1：按照要求创建数组，通过索引，其ar[4]、ar[:2,3:]、ar[3][2]分别是多少

hw_ar1 = np.arange(25).reshape(5,5)
print(hw_ar1)
print(hw_ar1[4])
print(hw_ar1[:2,3:])
print(hw_ar1[3][2])

#记住一个规则，不管是切片还是索引，参数1：向下，参数2：向右

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]
[[3 4]
 [8 9]]
17


In [63]:
#作业2：按照要求创建数组，筛选出元素值大于5的值并生成新的数组
hw_ar2 = np.arange(10).reshape(2,5)
print(hw_ar2)

x = hw_ar2 > 5
print(x)

print(hw_ar2[x])


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[False False False False False]
 [False  True  True  True  True]]
[6 7 8 9]
